### ISSUE TITLE
Dual weilding reload weapons

### ISSUE THREAD

**Issue by voodoozulu** [JDCalvert/FVTT-PF2e-Ranged-Combat#110]
When dual wielding reload weapons, almost all scenarios prevent you from firing the second weapon if the first weapon is unloaded. This may be an internal optimization in the PF2E module, by selecting the first of similar weapons. How to replicated:

-Create a character
-give this character 2 reloading weapons of the same type
-rename the weapons (to differentiate) I named them Weapon 1 and Weapon 2. This is optional.
-Equip Weapon 1 in one hand
-Equip Weapon 2 in one hand
-reload both weapons using the Ranged Combat macros

There are multiple ways to "fire" the weapon. 

-drag the individual item from the character sheet **actions** to your hot bar. No matter which weapon you drag, weapon 1 will always be fired instead of weapon 2. 
-Monk's Token bar adds a token bar to selected tokens. If you use Strikes -> Weapon 2. Weapon 1 will always be fired, even though you selected Weapon 2
-In character sheet, use the specific strike action for the weapon. This works, but I would prefer to be able to fire weapon 2 with a macro. This doesn't seem possible.

**Comment by JDCalvert** [comment]
Hi there, when you mention Monk's TokenBar, do you mean Token Action HUD instead? That's the only module I know of that fits the description you gave.

Unfortunately, I think this is a limitation of both the PF2e system and the TAH module at the moment rather than my module. The name you give to the weapon doesn't seem to matter, the base weapon's name is what's used to generate the strike's identifier, so it always finds the first item with that base type.

I'm afraid all I can suggest is writing a macro that specifically finds that strike, and posts it, or opening an issue in the [PF2e system](https://github.com/foundryvtt/pf2e/issues) to make the existing drag-drop macros work correctly.

**Comment by JDCalvert** [comment]
As a workaround for this issue, the PF2e system has recently added the ability to edit the slug of an item, which allows Token Action HUD to see them as different items.

Since this isn't a bug with this module, I'll close this for now.
