### ISSUE TITLE
[Bug/FeatureRequest] More specific Dialogue Text

### ISSUE THREAD

**Issue by Leolele99** [JDCalvert/FVTT-PF2e-Ranged-Combat#130]
The following is a small QoL "bug" report/feature request.
While not big issues, i think they are still important as this module is all about making ranged combat better to use.

### More specific Dialogue Text
Some of the scripts triggered by the macros use shared components like the _warning dialogue_ and  _item select dialogue_. They include some code for adjusted messages depending on the script that calls them, but I still noticed 2 cases, in which the dialogue text could be confusing, as it was intended for another use.

- The "Next Chamber" Macro, when attempting to switch to a chamber of the same ammunition type as is already Chamber Loaded (either by explicitly doing so through the select dialogue or when all loaded rounds are of the same type), throws the following warning.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/12782603/1b6ff53a-80f0-4896-bbff-276fc777edb4)
The "You cannot fire this weapon because:" string is a bit confusing here and promted me to check if the macro was misconfigured. Most people probably use the module in silent mode, and the notifications display only the error message so its not a problem there, but it might still help some.

- When using the "Unload" macro, the dialogue reads the following
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/12782603/1bdca4d5-91c2-417a-a456-ced5b40e1dc7)
For all other application, the "switching to" makes sense, but as this Macro does almost the opposite, users might think only the ammunition they select will remain. A small extra string for this exact case would help especially new players I think.

Thank you so much for working on this module, its great!

**Comment by JDCalvert** [comment]
I've improved the wording for the ammunition select dialog.

Due to the number of places that the generic warning dialog is used (since it's an intercept to the main warning system which simply states the error itself), it would be a huge amount of work to make it specific to the situation every time for, I think, very little benefit. Therefore, I've updated the wording to simply "You cannot perform this action because:" which at least means it makes sense everywhere, even though it's actually less specific.

These changes are in v4.0.2.
