### ISSUE TITLE
NPC strikes result in 'the item is not equipped' messages

### ISSUE THREAD

**Issue by venom986** [JDCalvert/FVTT-PF2e-Ranged-Combat#134]
When making a strike (either ranged or melee) with an NPC I keep getting the popup telling me that due to the Ranged Combat module I cannot use this strike as the item isn't equipped...except they are NPC strikes. I even tried equipping the related item, but that obviously didn't help since it's not really the object being used to generate the strike.

**Comment by JDCalvert** [comment]
Have you used the NPC Weapon Configuration macro for this NPC?

If the "Enable Advanced Thrown Weapon System" tickbox is checked, then each strike must be linked to a weapon in order to work. Admittedly, it's not clear that the setting will affect _all_ strikes, not only thrown weapon strikes, but it's worth checking.

**Comment by JDCalvert** [comment]
Closing since this has been open for a while with no response.
