### ISSUE TITLE
[Feature Request] Add button that triggers reload macro to Character Sheet

### ISSUE THREAD

**Issue by this-gavagai** [JDCalvert/FVTT-PF2e-Ranged-Combat#136]
Thanks for this great module.

Is there any possibility that the reload macro could be triggered directly from the character sheet rather than the macro toolbar? I'm finding that my players prefer interacting with their character sheet to the macro bar.

**Comment by JDCalvert** [comment]
The reason everything in this module is done with macros is because I have next to zero experience messing around with the HTML of the character sheet, so I can't make any promises, but I'll see what I can do next time I get a decent chunk of time (which won't be anytime in the next week I'm afraid).

I believe there's a new feature coming to the system soon that'll allow certain things to trigger when an action is posted to chat. With any luck, that'll be extendable enough to allow a macro to trigger, which would get you halfway there (it would still require a choice of weapon if you have multiple). I agree it would be nicest to have a button next to the Strike button.

**Comment by badgkat** [comment]
The simple way around this is simply to create an action named "Reload 1" put the reload icon on it and nest the macro in the description. Clicking the action then executes the macro. Probably easier than messing with the HTML and CSS of the sheets.

**Comment by JDCalvert** [comment]
I've finally had some time to look into this properly and have added buttons for reload, unload, reload magazine, and next chamber to the strikes in the character sheet! They should only show up when you can actually use them.

This has been released in v4.2.0, so please enjoy, and let me know if there are any issues!
