### ISSUE TITLE
Thrown weapon automation creates extra item stacks

### ISSUE THREAD

**Issue by tcm151** [JDCalvert/FVTT-PF2e-Ranged-Combat#161]
When using the thrown weapon automation, it creates an extra item in the inventory with 0 quantity.

For example, with the use of javelins, hatchets, or daggers:
1. Add 3 of one of the weapons in a stack to your inventory
2. Draw the weapon (one stack is worn, one stack is held)
3. Make a ranged strike and throw the weapon
4. This creates a third stack that is frustrating and confusing for players to have to deal with (one stack held with 0 quantity, one stack worn, and one stack dropped)

Example screenshot of inventory after said procedure:
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/48026413/c29e83ed-20c8-463d-bd7a-ff62dcfbe4e5)

**Comment by JDCalvert** [comment]
I'm afraid leaving the "held" stack is necessary because that's what the Strike is attached to. If it's deleted, then the damage buttons on the character sheet are gone and the damage buttons on the Strike in the chat won't work either.

However, I'll keep this around because I should be able to add buttons to draw, pick up, or just remove onto the empty stack, which will make them easier to deal with.

**Comment by JDCalvert** [comment]
I've now released this in v5.1.0, and there's not much else to be done about the issue, so closing for now.
