### ISSUE TITLE
[Bug] Hunt Prey Macro Not Setting Rule Option

### ISSUE THREAD

**Issue by 117ksk** [JDCalvert/FVTT-PF2e-Ranged-Combat#191]
Looks like with latest version of Hunt Prey macro, the roll option "Target is Your Hunted Prey" no longer turns on automatically when you target your hunted prey.

https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/113755707/8ead4f11-4afb-4070-9837-bb819aa3a7bd

**Comment by JDCalvert** [comment]
I changed it in a recent update. The module ticking the box was always a bit dodgy because if someone else (e.g. the GM) also selected the character it would untick the box.

With the new way, the bonuses will apply correctly if you're targeting your prey when you make the roll. 

If you're seeing any problems with the new way, please let me know!
