### ISSUE TITLE
Unable to Fire Custom Repeating Weapons

### ISSUE THREAD

**Issue by nrllewellyn** [JDCalvert/FVTT-PF2e-Ranged-Combat#195]
Steps to Reproduce:

1. Create a custom weapon. Name it "testweapon" Give it the repeating trait.
2. Give the weapon to a character
3. Give the character a magazine ammo
4. Equip the weapon
5. Go to the actions page and load the weapon
6. Try to fire

Behavior:
- The "Magazine Loaded" effect is properly applied to the character
- A pop-up displays "You cannot perform this action because: testweapon is not loaded"

Other details:
- This is being attempted as the DM selecting a player character
- Advanced Ammunition System is enabled
- The error message is odd, since it's the "weapon not loaded" error and not the "magazine not loaded" one
- The effect's text has a blank UUID in it:
  ```
  Your weapon is loaded with a magazine.
  @UUID[null]
  ```

Troubleshooting attempted:
- Via the console, I verified the the player character has the correct effect and that `game.actors.get("PC-UUID-here").itemTypes.effect[magazine-effect-index-here].flags["pf2e-ranged-combat"].targetId` matches the weapon's UUID in the PC's inventory

Tested with:
- Foundry: v12 Build 330
- System: PF2e 6.1.3
- Pf2e Ranged Combat: 6.3.4

**Comment by JDCalvert** [comment]
I haven't had chance to look at this properly yet, but off the top of my head, have you given the weapon a reload trait? Even if you want the reload to be 0, you need to give it the "reload 0" trait. Without that, the module probably gets an undefined value for reload and won'tb handle things correctly.

**Comment by nrllewellyn** [comment]
Sorry for the delay: I forgot that in my instructions, but the custom weapon _does_ have a reload trait. The scripts seem to apply the "Magazine loaded" effect correctly (I even verified the flags on the effect via the browser's console). It seems like the "on attack" hook doesn't realize that it's a magazine-fed weapon and is checking for the "Weapon loaded" effect instead of the "Magazine loaded" effect. (That's based purely off the error messages, but it seems to be the only option based on what I'm reading... JS isn't my primary language though... 😆 )

**Comment by JDCalvert** [comment]
I've done some more testing around this and things look _mostly_ okay to me. A couple of points/questions.

In the weapon details, what is the Reload Time set to? Repeating weapons with a Reload Time of more than 0 need to be reloaded with that many actions as well as having their magazine loaded (e.g. a repeating heavy crossbow). On the Attacks section on the character sheet, you should get a "Reload" button if it's needed.
![image](https://github.com/user-attachments/assets/6f42c3cc-da32-4b2a-a02c-3331e1cebb61)
![image](https://github.com/user-attachments/assets/bfafe79a-aaf6-464f-a13a-04a294e43fc6)

What ammunition were you using? The module requires that ammunition has a "Source ID". Ammunition you create from scratch or get from a module may not have this Source ID field. You can see this on an item's Rules tab:
![image](https://github.com/user-attachments/assets/6ed51edc-b03c-474d-a004-19c6e8880eee)

**Comment by SoilentBrad** [comment]
Because I had this problem last night, I can tell you that this occurs with the guns from the Starfinder playtest module. Had an error with the machine gun and plasma caster in our first combat, so I had to deactivate the "expend ammunition" setting, then later had to deactivate the module entirely.

**Comment by JDCalvert** [comment]
@SoilentBrad I've just had a look and the machine gun ammunition from that module is in fact missing a Source ID value, which explains the problem as I outlined in my previous comment.

I'm afraid there's not much I can do about that at the moment - the module is written with the expectation that items are set up in the same sort of format as the Pathfinder 2e system. You could probably write a quick script to update everything in a compendium to set its source ID to the same value as its ID in the compendium, but you'd have to run that every time you update the module.

**Comment by Sniperfox47** [comment]
Was using this last night and was thrown off for a minute, but after playing around it seems to work as intended.

The Starfinder firearms do not behave like PF2e firearms, in that they have a Magazine property and Reload property that refers to changing whole magazine, rather than the Repeating trait, which has a fixed 1 action Reload for the magazine, and a Reload property that refers to changing between rounds.

If you want the Starfinder firearms to work there's a two ways to do it depending on whether you want to modify the reload value:

1. Add the "Reloaded" trait, click "reload magazine" to load a magazine, and then click "reload" before each shot as a free action.
    - This will give you a "Magazine Loaded" effect that tracks ammo, plus a "Loaded" effect and allow you to fire.
    - This keeps the item mostly as is so it can properly take future updates to the SF2e module, but would break action tracking.
2. Add the "Reloaded" trait, change the "Reload" property to 0, and then click "reload magazine"
    - This gives you a "Magazine Loaded" effect that tracks ammo, and lets you fire until it runs out.
    - This means changing the item more so will be harder to maintain but makes everything else work as expected.
As mentioned, even if you do this it cannot be unloaded/reloaded. In order to unload it you need to manually delete the effect (and add a magazine with the remaining ammo manually), and in order to reload it you need to delete the effect and use the reload magazine button.

@JDCalvert is there a reason you're using the sourceID rather than the UUID? Source ID is something very specific to the PF2e system's internal compendiums, and is generated by their system migration process. It will never be present on 3rd party compendiums.

Have you considered using the object's `._source._stats.compendiumSource` instead? That's the same value that's stamped onto the Source ID field by the migration process and will be much more reliable for 3rd party ammo.

**Comment by JDCalvert** [comment]
@Sniperfox47 as far as I know `._source._stats.compendiumSource` is a new thing in Foundry v12. I've not had a lot of free time since v12 came out, and I haven't migrated to v12 in my games yet, so I've been trying to keep the module compatible with both v11 and v12. Making this change would either mean breaking compatibility with v11, or at least spending some time making sure whatever I did remained compatible with both.

I plan on getting things working properly for Starfinder at some point, but if possible I plan to wait until the actual module is out, since things may change drastically from the playtest. If I get a decent chunk of free time before then, I may look into it earlier.

**Comment by Sniperfox47** [comment]
Made a custom version of 6.3.5 that uses uuid rather than source id, to enable custom bullets, but it obviously breaks if you run out of ammo while the ammunition deletion system is enabled (since the ammo's UUID will be gone), and it has some weird behaviors with unloading.
Will serve my groups needs well enough, but not really suited for a more general deployment so I'm not going to make a PR or anything. You can find it here if there's any curiosity: https://github.com/Sniperfox47/FVTT-PF2e-Ranged-Combat/tree/6.3.5

**Comment by JDCalvert** [comment]
The system has been updated (as of [6.3.0](https://github.com/foundryvtt/pf2e/releases/tag/6.3.0)) to use `._source._stats.compendiumSource` instead of `flags.core.sourceId`. After a little bit of testing, it looks like this has fixed the issue.

I'm not sure if existing items have had a migration done so this value is set (e.g. if a world was updated from v11 to v12) but I'll consider this issue now closed.
