### ISSUE TITLE
Feature Request: Add a setting to obfuscate the name of an unknown actor

### ISSUE THREAD

**Issue by Syven88** [JDCalvert/FVTT-PF2e-Ranged-Combat#44]
I notice that when hunt prey is applied, it calls out the name of the actor. I find that sometimes I would like my players to succeed at recall knowledge checks to identify things that aren't immediately obvious, so having a setting to control whether they see the actor name or perhaps the token name would be helpful instead of only being limited to the actor name. 

So for example, instead of immediately outputting "...makes Goblin their hunted prey." it might say "...makes green-skinned humanoid their hunted prey."

**Comment by JDCalvert** [comment]
Hi there, thanks for the request, although I've had a look and the Hunt Prey message does already use the token name, rather than the actor name, so you could make the token named "small green-skinned humanoid" and that's what would appear in the chat message.

Obviously that's a little more work as a GM, but I can't think of a better way of doing it at the moment. I briefly considered using actor traits but, in some cases, they give away much more information than a name.

I'll leave this issue open. If you have any other suggestions on how this could work, please let me know!

**Comment by JDCalvert** [comment]
@Syven88 I think the [PF2e Workbench](https://github.com/xdy/xdy-pf2e-workbench) module does what you want - you can automatically mystify token names (even if they're not shown to players) and these names will be used when referring to that token.
