### ISSUE TITLE
Support for different ammunition per barrel

### ISSUE THREAD

**Issue by Ro4m3r** [JDCalvert/FVTT-PF2e-Ranged-Combat#58]
Currently different types of ammunition per barrel is not supported, and an error message is thrown.

If this were to be implemented, it would probably require different handling depending on the type of weapon used.

* **Double Barrel Weapons**
Some kind of selection screen when firing a double barrel weapon that has more than 1 bullet loaded, unless both bullets are the same. The double barrel firing mode would need to output both types of ammunition to chat if they are different. If they are the same, a single note would probably suffice.

* **Capacity**
If all bullets in the weapon are the same, again, nothing needs to change. If the weapon contains multiple barrels, the Next Barrel macro would need a selection screen to determine to which barrel the player wants to switch.

* **Unloading**
The unload macro for double barrel and capacity weapons would need to show a selection screen for which bullet to unload, again, only if the weapon contains ammunition of differing types.
**There is a special edge case here:** When the next barrel has been selected and the gun is ready to fire, but is loaded with a piece of ammunition of which there is currently only 1 type in the gun, and the player unloads it, the next barrel buff needs to be removed, as the player has removed the piece of ammunition that is at the current barrel.
Here are two more concrete example:
`A pepperbox that was just fired is loaded with 2 rounds and 1 meteor shot. The player uses the Next Barrel action and selects the meteor shot. The player unloads the meteor short. The Next Barrel buff needs to be removed in this case.`
`A pepperbox that was just fired is loaded with 2 rounds and 2 meteor shot. The player uses the Next Barrel action and selects the meteor shot. The player unloads the meteor short. The Next Barrel buff does **not** need to be removed in this case as it can be assumed that the player would unload the round that is **not** the one in the currently selected barrel.`

I hope that covers all cases, but there could be things I missed.

**Comment by JDCalvert** [comment]
I thought about this when originally writing the capacity functionality. The potential problems I thought of were:

### Capacity Weapons
The capacity trait text says "the next loaded barrel or chamber", and this doesn't require a free hand. There are a couple of interpretations for this:
1. There is a lever (or something) on the weapon that selects the next barrel. This doesn't necessarily give a choice of which barrel is next.
2. The lever allows you to select a specific barrel, which is how you can always select a loaded barrel.

I think I side with option 2, as otherwise the weapon would have to have a way of detecting which barrels/chambers are loaded, which seems unlikely.

### Double-Barreled Weapons
If each barrel is loaded with different ammunition, how does this interact with firing both barrels at once? There are few scenarios to consider:

* One barrel with special ammunition, one with regular ammunition
* Both barrels with the same special ammunition
* Each barrel with different special ammunition

At least for most cases, the answer should be fairly simple: leave it up to the GM. The module can ignore what the ammunition is, post both pieces of ammunition (if different) and apply the normal damage increase from firing both barrels. The GM can then decide how the special ammunition applies.

**Comment by Ro4m3r** [comment]
I'm not sure how other tables handle it, but I don't think very many people track the *order* of the barrel on capacity weapons, meaning I would also go with option 2. Regardless, if a selection screen is implemented, GMs can handle handle it however they want, either letting a player choose whatever barrel they want, or telling them they need to track the order and always select the "next" one in the screen.

I think posting them to chat is enough for double-barrel weapons, I would personally rule it as applying the effects of both ammunitions, since it doesn't really make any sense to me from a logical, in-world perspective otherwise (why would only one be applied when firing both?). But leaving it up to the GM is always a good idea.

**Comment by JDCalvert** [comment]
Released in 2.7.0!
